name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa o workflow diariamente

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v2
        with:
          github_user_name: djrenanzinho
          outputs: |
